CREATE TABLE [dbo].[BUSQUEDAS]
(
	[ID_BUSQUEDA] INT IDENTITY(1,1) NOT NULL, 
    [EMPRESA_BUSCADA] NVARCHAR(50) NOT NULL, 
    [RESULTADO_BUSQUEDA] INT NOT NULL, 
    [FECHA_BUSQUEDA] DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT [PK_BUSQUEDA] PRIMARY KEY CLUSTERED ([ID_BUSQUEDA] ASC)
)
GO
