CREATE TABLE [dbo].[USUARIO_BUSQUEDA]
(
	[FK_USUARIO] NVARCHAR(50) NOT NULL, 
    [FK_BUSQUEDA] INT NOT NULL,
	CONSTRAINT [FK_USUARIO] FOREIGN KEY(FK_USUARIO) REFERENCES USUARIOS (EMAIL),
	CONSTRAINT [FK_BUSQUEDA] FOREIGN KEY(FK_BUSQUEDA) REFERENCES BUSQUEDAS (ID_BUSQUEDA)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
