CREATE TABLE [dbo].[USUARIOS]
(
	[EMAIL]NVARCHAR(50) NOT NULL, 
    [NOMBRE] NVARCHAR(50) NOT NULL, 
    [APELLIDOS] NVARCHAR(50) NOT NULL, 
    [PASSWORD] NCHAR(10) NOT NULL,
    [FECHANACIMIENTO] DATETIME NOT NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([EMAIL])
)
GO